### ISSUE TITLE
disk_usage needs a fact

### ISSUE THREAD

**Issue by andreramoni** [andreramoni/puppet-trollme#12]
disk_usage runs on every agent run. The class should compare the configured value with a fact, so it wouldn't trigger the exec overtime.
It should be a structured fact, with mount points and their usage.

**Comment by FCO** [comment]
Something like this?

```df -a | perl -F'\s+' -nale 'next if $. == 1; print "$F[-1]=$1" if $F[-2] =~ /^(\d+)%$/'```

**Comment by andreramoni** [comment]
Fixed.
